ViewModel for LoginScreen
Flobsterable/pets-project pull request #3
Opened 2022-07-01 12:37 UTC by Flobsterable

2022-07-04 02:50 UTC, nbaklanov-issart requested changes

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/LoginScreen.kt
> +        )
Так использовать Sealed классы и передавать так каллбэки - интересный способ, не могу сказать плохо это или хорошо, но использование такого подхода определенно показывает, что есть понимание как оно работает.

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/LoginScreen.kt
> +    onClick : (Int)-> Unit
Я стараюсь для всех типов коллбэков заводить  typealias чтобы использовать типы замыканий, как обычный тип.

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +    override fun obtainEvent(event : LoginEvent){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +        when(event){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +    private fun emailChanged(value: String){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +    private fun passChanged(value: String){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +    private fun passConfirmationChanged(value: String){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +        val email : String = viewState.value?.emailValue!!
: выделяется двойным пробелом при наследовании. Тут просто email: String

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +        with(viewState){
Пробел меджу ) и {

2022-07-04 02:50 UTC, nbaklanov-issart commented on app/src/main/java/com/example/pets_project/ui/screens/login/model/LoginViewModel.kt
> +class LoginViewModel @Inject constructor()
Здесь просто общий момент:

Чтобы постоянно не таскать текущее значение из _viewModel, я держу экземпляр текущего состояния вьюхи (LoginViewState) как свойство LoginViewModel и когда нужно просто изменяю его и отправляю его в _viewModel. Но это кому как удобно.

2022-07-05 11:48 UTC, Nikolaiko approved these changes

2022-07-05 11:48 UTC, merged